### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by vgsk** [OpenInformix/node-informixdb#10]
Just wondering if it would be possible for you to include typescript support into the module with examples and necessary type declaration ?

I am currently using the module and it worked just fine putting my own declaration file (.d.ts) in my earlier project (typescript 3.7.3) and the same is not working in my project (typescript 4.1.2). I am not able to use it like

import db from 'informixdb';

It give me an error even after have a declaration file informixdb.d.ts in the same directory with 

declare module 'informixdb';

[undefined] uncaughtException: ⨯ Unable to compile TypeScript:
src/informix-db-connection.ts:2:16 - error TS7016: Could not find a declaration file for module 'informixdb'. '/home/vgsk/WORK/LoadBuilder/lb-api-server/node_modules/informixdb/lib/odbc.js' implicitly has an 'any' type.
 Try `npm i --save-dev @types/informixdb` if it exists or add a new declaration (.d.ts) file containing `declare module 'informixdb';`

2 import db from 'informixdb';
                ~~~~~~~~~~~~

I have the following in the tsconfig.json

    "include": [
        "src/**/*"
    ],    

         
Would appreciate it if you could help.

**Comment by rhtpandeyIN** [comment]
Hi @vgsk , thanks for the feedback and new suggestions. Our team is quite busy nowadays in some other priority works, and due to the "year-end," most of our Engineers are on leave :)

So we will get back to you with a more positive response next year.

Regards:
Rohit

**Comment by rhtpandeyIN** [comment]
>Also, a quick question. Wanted to know if the module would support collections (set data type).

Yes, we have that in the pipeline. By late Jan 2020 you can expect that coming.

**Comment by notchris** [comment]
Is this still going to be added?
